import test from 'node:test';
import assert from 'node:assert/strict';
import {CARDS,TYPES,initialState,newSession,draw,replaceCard,complete,setSlotStatus,score,spent,target,thresholds,eligible,undo,togglePause,elapsed,finish,validateBackup} from '../dist/core.mjs';
import {renderView} from '../dist/views.mjs';
function started(mode='short',budget=0,place='both'){const s=initialState();newSession(s,{...s.preferences,mode,budget,place},1000000);return s;}
function done(s,i=0,time=1000100){const se=s.session,x=se.slots[i];draw(s,se.id,x.id,null,()=>0);complete(s,se.id,x.id,x.card.id,0,time);return x;}
test('48 unique cards preserve 24 original cards and balanced pools',()=>{assert.equal(CARDS.length,48);assert.equal(new Set(CARDS.map(x=>x.id)).size,48);assert.equal(CARDS.filter(x=>x.source==='original').length,24);for(const type of Object.keys(TYPES))assert.equal(CARDS.filter(x=>x.type===type).length,16);});
test('short and half plans have reachable target and thresholds',()=>{let s=started();assert.equal(target(s.session),13);assert.deepEqual(thresholds(s.session),[8,11,13]);s=started('half');assert.equal(target(s.session),20);assert.deepEqual(thresholds(s.session),[12,16,20]);for(let i=0;i<7;i++)done(s,i,1000100+i);const id=s.session.id;finish(s,id,{name:'晚风',memory:'一起走',closing:true},1001000);assert.equal(score(s.history[0]).base,16);assert.equal(score(s.history[0]).total,22);});
test('same completed card cannot receive points twice',()=>{const s=started(),x=done(s),before=score(s.session).total;assert.equal(complete(s,s.session.id,x.id,x.card.id),false);assert.equal(score(s.session).total,before);});
test('draw and replace reject stale cards; replaced cards never reappear',()=>{const s=started(),se=s.session,x=se.slots[0];draw(s,se.id,x.id,null,()=>0);const old=x.card.id;assert.throws(()=>draw(s,se.id,x.id),/抽过/);replaceCard(s,se.id,x.id,old,()=>0);assert.notEqual(old,x.card.id);assert.throws(()=>replaceCard(s,se.id,x.id,old),/变化/);assert(!eligible(s,'scene').some(c=>c.id===old));});
test('exhausted card pool leaves current card intact',()=>{const s=started(),se=s.session,x=se.slots[0];draw(s,se.id,x.id,null,()=>0);s.disabled=CARDS.map(c=>c.id);const before=structuredClone(x);assert.throws(()=>replaceCard(s,se.id,x.id,x.card.id),/用完/);assert.deepEqual(x,before);});
test('budget and location filters include only suitable tasks',()=>{const s=started('short',0,'indoor');assert(eligible(s,'event').every(c=>c.cost===0&&c.place!=='outdoor'));assert(eligible(s,'scene').every(c=>c.place!=='outdoor'));s.session.budget=40;const x=s.session.slots[2];s.disabled=CARDS.filter(c=>c.type==='event'&&c.id!=='event-05').map(c=>c.id);draw(s,s.session.id,x.id);complete(s,s.session.id,x.id,x.card.id,35);assert.equal(spent(s.session),35);assert(eligible(s,'event').every(c=>c.cost<=5));});
test('trio award recalculates on undo and cannot stack',()=>{const s=started();done(s,0,1000100);done(s,1,1000101);done(s,2,1000102);assert.equal(score(s.session).trio,2);const id=undo(s,s.session.id);assert.equal(id,s.session.slots[2].id);assert.equal(score(s.session).trio,0);const x=s.session.slots[2];complete(s,s.session.id,x.id,x.card.id);assert.equal(score(s.session).trio,2);});
test('deferred card stays in same session and can be completed later',()=>{const s=started(),se=s.session,x=se.slots[0];draw(s,se.id,x.id);setSlotStatus(s,se.id,x.id,'later');done(s,1);complete(s,se.id,x.id,x.card.id);assert.equal(score(se).count,2);});
test('skipping yields no points and preserves original goal',()=>{const s=started(),se=s.session;setSlotStatus(s,se.id,se.slots[0].id,'skipped');assert.equal(score(se).total,0);assert.equal(target(se),13);});
test('pause excludes time, blocks drawing, and closes cleanly',()=>{const s=started(),id=s.session.id;togglePause(s,id,1060000);assert.equal(elapsed(s.session,1600000),60000);assert.throws(()=>draw(s,id,s.session.slots[0].id),/继续/);togglePause(s,id,1120000);assert.equal(elapsed(s.session,1180000),120000);togglePause(s,id,1180000);finish(s,id,{name:'休息',memory:'',closing:false},1240000);assert.equal(elapsed(s.history[0]),120000);assert.equal(s.history[0].pausedAt,null);assert.throws(()=>finish(s,id,{}),/变化/);});
test('free mode selects types and has no fixed goal',()=>{const s=started('free');draw(s,s.session.id,null,'talk',()=>0);assert.equal(s.session.slots[0].type,'talk');assert.equal(target(s.session),0);assert.deepEqual(thresholds(s.session),[]);});
test('backup roundtrip retains active session, settings and histories',()=>{const s=started();done(s);s.preferences.rewards=['茶','小花','晚餐'];const clean=validateBackup(JSON.parse(JSON.stringify(s)));assert.deepEqual(clean.session,s.session);assert.deepEqual(clean.preferences,s.preferences);finish(s,s.session.id,{name:'散步',memory:'故事',closing:true},1002000);assert.deepEqual(validateBackup(s).history,s.history);});
test('malformed and hostile backups fail before mutation',()=>{const original=started();for(const mutate of [s=>s.version=99,s=>s.history=null,s=>s.session.id='" onclick="alert(1)',s=>s.session.startedAt=1e30,s=>s.session.slots[0].type='__proto__',s=>s.session.slots=[],s=>s.session.bonuses.laugh='yes']){const bad=structuredClone(original);mutate(bad);assert.throws(()=>validateBackup(bad));}assert.equal(original.version,1);});
test('all views render meaningful states and escape user prose',()=>{const s=started();done(s);const ui={libraryType:'all',libraryFavorites:false,customEditor:true,offlineReady:true,focusSlot:null};for(const route of ['home','setup','walk','finish','library','history','settings']){const html=renderView(s,ui,route);assert(html.includes('<main>'));assert(!html.includes('undefined'));assert(!html.includes('NaN'));}const id=finish(s,s.session.id,{name:'<img onerror=alert(1)>',memory:'<script>bad</script>',closing:true},1002000);const html=renderView(s,ui,'detail',id);assert(html.includes('&lt;img'));assert(!html.includes('<script>bad'));});
