<script lang="ts">
 import type {GameState,UIState} from '../lib/config/types';
 import {allCards,TYPES} from '../lib/domain/core.mjs';
 import {cardArt} from '../lib/ui/art.mjs';
 import {asset} from '../lib/config/assets';
 import PageHead from '../lib/components/PageHead.svelte';
 import ActionButton from '../lib/components/ActionButton.svelte';
 import Achievements from '../lib/components/Achievements.svelte';
 import {completedCards} from '../lib/domain/collection.mjs';
 import CardEditor from '../lib/components/CardEditor.svelte';
 let {state,ui}:{state:GameState;ui:UIState}=$props();
 let completed=$derived(completedCards(state));
 let all=$derived(allCards(state)),cards=$derived(all.filter(card=>(ui.libraryType==='all'||card.type===ui.libraryType)&&(!ui.libraryFavorites||state.favorites.includes(card.id))&&(!ui.libraryCompleted||completed.has(card.id))&&(!ui.libraryDisabled||state.disabled.includes(card.id))));
 const names:Record<string,string>={scene:'探索委托',talk:'双人对话',event:'挑战任务'};
</script>
<div class="page wide"><PageHead title="任务收藏册"/><div class="collection-cover"><img src={asset('card-back.webp')} alt="" width="64" height="86"><div><p class="eyebrow">双人冒险 · 任务收藏册</p><p>把想做的事，留给下一程。</p><span class="small muted">{all.length} 张任务 · {state.favorites.length} 张喜欢</span></div></div><div class="chips collection-tabs" role="group" aria-label="任务筛选">{#each [['all','全部'],...Object.keys(TYPES).map(key=>[key,names[key]])] as [key,label]}<button type="button" class={`chip ${ui.libraryType===key?'active':''}`} aria-pressed={ui.libraryType===key} data-action="filter-type" data-type={key}>{label}</button>{/each}<button type="button" class={`chip ${ui.libraryFavorites?'active':''}`} aria-pressed={ui.libraryFavorites} data-action="filter-favorites">只看喜欢</button><button type="button" class={`chip ${ui.libraryCompleted?'active':''}`} aria-pressed={ui.libraryCompleted} data-action="filter-completed">完成过</button><button type="button" class={`chip ${ui.libraryDisabled?'active':''}`} aria-pressed={ui.libraryDisabled} data-action="filter-disabled">不抽</button></div><p class="help">最近三局完成的任务会少抽一点；仍可再次遇见。“不抽”的任务会一直排除。</p><Achievements {state}/><ActionButton label={ui.customEditor?'收起自定义卡':'＋ 写一张自己的卡'} action="show-editor" kind="outline"/><div class="spacer"></div>{#if ui.customEditor}<CardEditor/>{/if}<p class="small muted" role="status">{cards.length} 张任务</p><div class="collection-grid">{#each cards as card (card.id)}{@const art=cardArt(card)}{@const disabled=state.disabled.includes(card.id)}{@const favorite=state.favorites.includes(card.id)}<article class={`collection-card ${card.type}${disabled?' card-shelved':''}`}><div class="collection-art"><img src={asset(art.src)} alt={art.alt} loading="lazy" decoding="async" width="120" height="160"><span>{names[card.type]}</span></div><div class="collection-copy"><div class="list-top"><span class="small muted">{card.id.startsWith('custom-')?'我们写的':`NO. ${card.id.split('-')[1]}`}</span>{#if disabled}<span class="shelved-label">暂不抽取</span>{/if}</div><h2>{card.text}</h2>{#if completed.has(card.id)}<p class="help completed-label">✓ 完成过 {completed.get(card.id)} 次</p>{/if}{#if card.note}<p class="help">{card.note}</p>{/if}<p class="help">约 {card.minutes} 分钟 · {card.cost?`预算 ¥${card.cost} 内`:'无需花费'}</p><div class="actions"><ActionButton label={favorite?'♥ 已喜欢':'♡ 喜欢'} action="favorite" kind="text" attrs={{'data-card':card.id,'aria-pressed':favorite}}/><ActionButton label={disabled?'重新加入':'暂时不抽'} action="disable-card" kind="text" attrs={{'data-card':card.id,'aria-pressed':disabled}}/></div></div></article>{:else}<div class="panel empty"><h2>这一页还空着</h2><p>换个筛选，或为喜欢的任务点一颗心。</p></div>{/each}</div></div>
