<script lang="ts">
 import type {GameState,UIState} from '../lib/config/types';
 import PageHead from '../lib/components/PageHead.svelte';
 import ActionButton from '../lib/components/ActionButton.svelte';
 let {state,ui,release}:{state:GameState;ui:UIState;release:string}=$props();
</script>
<div class="page"><PageHead title="设置"/><div class="settings-intro"><p class="eyebrow">出发前的小准备</p><p>奖励、备份和离线，都在这里。</p></div>
<section class="panel"><h2>版本与更新</h2><p class="help">当前版本 <span data-current-version>{release}</span></p><p class="status-line" data-update-status role="status">{ui.updateMessage}</p><div class="spacer"></div><div class="actions"><ActionButton label={ui.updateChecking?'正在检查…':'检查更新'} action="check-update" kind="outline" attrs={{disabled:ui.updateChecking}}/><ActionButton label="应用更新并刷新" action="apply-update" kind={`secondary ${ui.updateWaiting?'':'hidden'}`}/></div><p class="help">更新保留本机散步、分数、主题与历史。正在进行的一局也可以更新。</p></section>
<section class="panel"><h2>声音</h2><p class="help">翻牌、盖章与达档的短提示音，默认关闭。返回后台会暂停声音。</p><ActionButton label={state.sound?'关闭声音':'开启声音'} action="toggle-sound" kind="outline" attrs={{'aria-pressed':state.sound}}/></section>
<section class="panel"><h2>主题</h2><div class="theme-options" role="group" aria-label="主题"><button type="button" class="theme-option" aria-pressed="true" data-action="set-theme" data-theme-choice="adventure"><span class="theme-option-title">双人冒险 <span class="theme-selected">使用中</span></span></button><button type="button" class="theme-option" disabled aria-disabled="true"><span class="theme-option-title">暖日散步</span><span class="theme-description">暂未开放</span></button></div></section>
<form class="panel" id="reward-form"><h2>奖励</h2><p class="help">按从小到大填写。用于下一局，进行中的散步保留原设置。</p>{#each state.preferences.rewards as reward,i}<label for={`reward-${i}`}>第{i+1}档奖励</label><input id={`reward-${i}`} name={`reward${i}`} value={reward} maxlength="80" required>{/each}<div class="spacer"></div><button class="btn block secondary" type="submit">保存奖励</button></form>
<section class="panel"><h2>备份与恢复</h2><p class="help">记录保存在当前浏览器。无痕模式、清理网站数据或更换手机可能让记录丢失。导出备份后可在另一部手机导入。</p><div class="spacer"></div><div class="actions"><ActionButton label="导出备份" action="export" kind="outline"/><ActionButton label="导入备份" action="import" kind="outline"/></div><input type="file" id="backup-file" accept=".json,application/json" class="hidden"><p class="help">导入会替换当前设备全部记录，请先备份。Safari导出的文件通常在“文件”App的下载目录。</p></section>
<section class="panel"><h2>添加到手机桌面</h2><p><strong>苹果：</strong>在Safari打开网址，点分享按钮，选择“添加到主屏幕”。</p><p><strong>安卓：</strong>在浏览器菜单中选择“安装应用”或“添加到主屏幕”。不同浏览器名称可能不同。</p><p class="help">从桌面图标首次打开时请保持联网，等待离线准备完成。网页和桌面入口的存储可能因浏览器而异，开始前先检查记录。</p><p class="status-line" data-offline>{ui.offlineReady?'✓ 离线内容已准备好':'离线内容尚未准备好，请联网打开并等待片刻。'}</p><div class="spacer"></div><ActionButton label="检查离线内容" action="check-offline" kind="outline"/><p class="help">锁屏期间不保证准点提醒；回来后会重新计算时间。需要准点提醒时，可以设置手机闹钟。</p></section>
<section class="panel"><details><summary>怎么玩，怎么算分？</summary><p>场景卡和对话卡每张2分，事件卡每张3分。三类各完成一张，奖励2分，每局一次。两人确认的“惊喜”和“爆笑”各加1分，每种一次。</p><p>结束时各分享一个喜欢的瞬间，再为散步取名，完成收尾加4分。短途默认目标13分，半日20分。完成计划和收尾就能达到，不依赖额外奖励。</p><p>跳过不扣分，目标也不会降低。换过的卡本局不再出现。奖品按最高达成档领取，也可以关闭计分，只管一起走走。</p></details></section></div>
