import {allCards,TYPES,score,elapsed} from '../domain/core.mjs';
import {cardArt} from './art.mjs';
const names={scene:'探索委托',talk:'双人对话',event:'挑战任务'};
export function collectionView(s,ui,{esc,button,editor}){
 const all=allCards(s),cards=all.filter(c=>(ui.libraryType==='all'||c.type===ui.libraryType)&&(!ui.libraryFavorites||s.favorites.includes(c.id)));
 return `<div class="collection-cover"><img src="./card-back.webp" alt="" width="64" height="86"><div><p class="eyebrow">双人冒险 · 任务收藏册</p><p>把想做的事，留给下一程。</p><span class="small muted">${all.length} 张任务 · ${s.favorites.length} 张喜欢</span></div></div>
 <div class="chips collection-tabs" role="group" aria-label="任务筛选">${[['all','全部'],...Object.keys(TYPES).map(k=>[k,names[k]])].map(([v,t])=>`<button type="button" class="chip ${ui.libraryType===v?'active':''}" aria-pressed="${ui.libraryType===v}" data-action="filter-type" data-type="${v}">${t}</button>`).join('')}<button type="button" class="chip ${ui.libraryFavorites?'active':''}" aria-pressed="${!!ui.libraryFavorites}" data-action="filter-favorites">只看喜欢</button></div>
 ${button(ui.customEditor?'收起自定义卡':'＋ 写一张自己的卡','show-editor','','outline')}<div class="spacer"></div>${ui.customEditor?editor():''}
 <p class="small muted" role="status">${cards.length} 张任务</p><div class="collection-grid">${cards.length?cards.map(c=>{
 const art=cardArt(c),disabled=s.disabled.includes(c.id),favorite=s.favorites.includes(c.id);
 return `<article class="collection-card ${c.type}${disabled?' card-shelved':''}"><div class="collection-art"><img src="./${art.src}" alt="${art.alt}" loading="lazy" decoding="async" width="120" height="160"><span>${names[c.type]}</span></div><div class="collection-copy"><div class="list-top"><span class="small muted">${c.id.startsWith('custom-')?'我们写的':`NO. ${c.id.split('-')[1]}`}</span>${disabled?'<span class="shelved-label">暂不抽取</span>':''}</div><h2>${esc(c.text)}</h2>${c.note?`<p class="help">${esc(c.note)}</p>`:''}<p class="help">约 ${c.minutes} 分钟 · ${c.cost?`预算 ¥${c.cost} 内`:'无需花费'}</p><div class="actions">${button(favorite?'♥ 已喜欢':'♡ 喜欢','favorite',`data-card="${esc(c.id)}" aria-pressed="${favorite}"`,'text')}${button(disabled?'重新加入':'暂时不抽','disable-card',`data-card="${esc(c.id)}" aria-pressed="${disabled}"`,'text')}</div></div></article>`;
 }).join(''):'<div class="panel empty"><h2>这一页还空着</h2><p>换个筛选，或为喜欢的任务点一颗心。</p></div>'}</div>`;
}
export function journalView(s,{esc,navBtn,fmtDate,timeText}){
 return `<div class="journal-cover"><img src="./explorer-badge.webp" alt="" width="64" height="64"><div><p class="eyebrow">双人冒险 · 冒险日志</p><p>${s.history.length?`我们一起走过 ${s.history.length} 程。`:'第一段故事，等你们出发。'}</p></div></div>
 <div class="journal-list">${s.history.length?s.history.map((h,i)=>`<article class="journal-entry"><div class="journal-index" aria-hidden="true">${String(s.history.length-i).padStart(2,'0')}</div><div class="journal-entry-body"><div class="list-top"><span class="small muted">${fmtDate(h.startedAt)}</span><span class="record-score">${h.scoring?`${score(h).total} 分`:`${score(h).count} 张`}</span></div><h2>${esc(h.name)}</h2><p class="help">同行 ${timeText(elapsed(h))} · 完成 ${score(h).count} 张任务</p>${h.memory?`<p class="journal-excerpt">${esc(h.memory.slice(0,90))}${h.memory.length>90?'…':''}</p>`:''}${navBtn('翻开这一程',`detail/${esc(h.id)}`,'text')}</div></article>`).join(''):`<div class="panel empty"><img class="journal-empty-art" src="./journey-departure.webp" alt="两人准备开启城市冒险" width="960" height="640"><h2>下一程，从今天开始</h2>${navBtn('去走走',s.session?'walk':'setup')}</div>`}</div><p class="footnote">回忆保存在这部设备上，换手机前记得导出备份。</p>`;
}
