import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';

export async function prepareRelease(directory,{check=false}={}){
 const files=(await fs.readdir(directory,{withFileTypes:true})).filter(f=>f.isFile()&&/\.(?:mjs|js|css|html|json|webmanifest|png|webp|svg|ico)$/.test(f.name)&&!['sw.js','release.mjs','package.json','package-lock.json'].includes(f.name)).map(f=>f.name).sort();
 const swPath=path.join(directory,'sw.js');
 const sw=await fs.readFile(swPath,'utf8');
 const list=['./',...files.map(f=>'./'+f),'./release.mjs'];
 const normalized=sw.replace(/const CACHE='[^']+';/,"const CACHE='__CONTENT_VERSION__';").replace(/const FILES=\[[^;]+;/,`const FILES=${JSON.stringify(list)};`).replace(/\r\n/g,'\n');
 const hash=createHash('sha256').update(normalized);
 for(const file of files){hash.update(file+'\0');const bytes=await fs.readFile(path.join(directory,file));hash.update(/\.(?:mjs|js|css|html|json|webmanifest)$/.test(file)?bytes.toString('utf8').replace(/\r\n/g,'\n'):bytes);}
 const version='r-'+hash.digest('hex').slice(0,12);
 const output=normalized.replace('__CONTENT_VERSION__','citywalk-static-'+version).replace(`const FILES=${JSON.stringify(list)};`,`const FILES=[${list.map(f=>"'"+f+"'").join(',')}];`);
 const release=`// Generated by npm run release. Content-based, no manual version bump.\nexport const RELEASE='${version}';\n`;
 if(check){
  if(sw.replace(/\r\n/g,'\n')!==output||(await fs.readFile(path.join(directory,'release.mjs'),'utf8')).replace(/\r\n/g,'\n')!==release)throw Error('Release stamp is stale. Run npm run release before publishing.');
 }else{await fs.writeFile(swPath,output);await fs.writeFile(path.join(directory,'release.mjs'),release);}
 return version;
}
if(process.argv[1]&&import.meta.url===pathToFileURL(path.resolve(process.argv[1])).href){
 const target=process.argv.slice(2).find(arg=>!arg.startsWith('--'));
 console.log(await prepareRelease(target?path.resolve(target):path.resolve(import.meta.dirname,'../dist'),{check:process.argv.includes('--check')}));
}
